apiVersion: v2
name: agent-control-deployment
description: A Helm chart to install New Relic Agent Control on Kubernetes

type: application

version: 1.2.1
appVersion: "1.7.1"

dependencies:
  - name: common-library
    version: 1.4.0
    repository: https://helm-charts.newrelic.com

keywords:
  - newrelic
  - agent-control

maintainers:
  # Agent Control Team
  - name: ac
    url: https://github.com/orgs/newrelic/teams/ac/members
