apiVersion: v2
name: agent-control-deployment
description: A Helm chart to install New Relic Agent Control on Kubernetes

type: application

version: 0.0.42-beta

keywords:
  - newrelic
  - agent-control

maintainers:
  - name: sigilioso
    url: https://github.com/sigilioso
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: kang-makes
    url: https://github.com/kang-makes
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur
