apiVersion: v2
name: pipeline-control-gateway
type: application
version: 1.2.1
dependencies:
  - name: common-library
    version: 1.4.0
    repository: https://helm-charts.newrelic.com
appVersion: "1.2.0"
maintainers:
  - name: pipeline-control
    url: https://github.com/orgs/newrelic/teams/pcon/members
