apiVersion: v2
name: pipeline-control-gateway
type: application
version: 1.0.0
dependencies:
  - name: common-library
    version: 1.1.1
    repository: "https://helm-charts.newrelic.com"
appVersion: "1.0.0"
maintainers:
  - name: pipeline-control
    url: https://github.com/orgs/newrelic/teams/pcon/members
    