apiVersion: v2
name: ping-runtime
description: New Relic Synthetics Ping Runtime
type: application
version: 1.0.0
appVersion: 1.3.1
home: https://github.com/orgs/newrelic/teams/proactive-monitoring
maintainers:
  - name: Philip-R-Beckwith
  - name: sshah-nr
  - name: vkasanneni-nr
  - name: marcusperezNR
  - name: mderemer-nr
  - name: kaschaefer-nr
  - name: sadafarshad
  - name: lromer22
    email: team_proactive-monitoring@newrelic.com
keywords:
  - synthetics
  - synthetics-job-manager
  - ping-runtime
  - newrelic
