{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "nri-metadata-injection.fullname" . }}
  labels:
{{- include "nri-metadata-injection.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "nri-metadata-injection.fullname" . }}
subjects:
  - kind: ServiceAccount
name: {{ template "nri-metadata-injection.serviceAccountName" . }}
namespace: {{ .Release.Namespace }}
{{- end }}
