apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "nri-metadata-injection.fullname" . }}
  labels:
{{- include "nri-metadata-injection.labels" . | nindent 4 }}
webhooks:
- name: metadata-injection.newrelic.com
  clientConfig:
service:
  name: {{ template "nri-metadata-injection.fullname" . }}
  namespace: {{ .Release.Namespace }}
  path: "/mutate"
caBundle: ""
  rules:
  - operations: [ "CREATE" ]
apiGroups: [""]
apiVersions: ["v1"]
resources: ["pods"]
{{- if .Values.injectOnlyLabeledNamespaces }}
  namespaceSelector:
matchLabels:
  newrelic-metadata-injection: enabled
{{- end }}
  failurePolicy: Ignore
  timeoutSeconds: {{ .Values.timeoutSeconds }}
