{{- if ( include "newrelic.compatibility.agentConfig" .) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-agent
data:
  newrelic-infra.yml: |-
    {{- include "newrelic.compatibility.agentConfig" . | nindent 4 -}}
{{- end -}}
