{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{- include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}
rules:
  - apiGroups: [""]
resources:
  - "nodes/metrics"
  - "nodes/stats"
  - "nodes/proxy"
verbs: ["get", "list"]
  - apiGroups: [ "" ]
resources:
  - "endpoints"
  - "services"
  - "nodes"
verbs: [ "get", "list", "watch" ]
  - nonResourceURLs: ["/metrics"]
verbs: ["get"]
  {{- if .Values.rbac.pspEnabled }}
  - apiGroups:
  - extensions
resources:
  - podsecuritypolicies
resourceNames:
  - privileged-{{ template "newrelic.fullname" . }}
verbs:
  - use
  {{- end -}}
{{- end -}}
