apiVersion: v2
name: job-manager
description: New Relic Job Manager for K8s-based Location Deployment
type: application
version: 1.0.0
appVersion: release-1
home: https://github.com/orgs/newrelic/teams/infraplat
maintainers:
  - name: nr-mdadhich
  - name: nr-mjuvvadi
  - name: shubhamgupta-dev
  - name: msivant
  - name: sbendict
    email: infraplusplatform@newrelic.com
keywords:
  - job-manager
  - newrelic
  - kubernetes
dependencies:
  - name: node-api-runtime
    version: 1.0.47
    condition: node-api-runtime.enabled
  - name: node-browser-runtime
    version: 2.0.12
    condition: node-browser-runtime.enabled
