apiVersion: v2
name: node-browser-runtime
description: New Relic Synthetics Browser Runtime
type: application
version: 2.0.12
appVersion: 3.0.55
home: https://github.com/orgs/newrelic/teams/infraplat
maintainers:
  - name: nr-mdadhich
  - name: nr-mjuvvadi
  - name: shubhamgupta-dev
  - name: msivant
  - name: sbendict
    email: infraplusplatform@newrelic.com
keywords:
  - synthetics
  - synthetics-job-manager
  - node-browser-runtime
  - newrelic
