apiVersion: v2
name: node-api-runtime
description: New Relic Synthetics Api Runtime
type: application
version: 1.0.47
appVersion: 1.2.134
home: https://github.com/orgs/newrelic/teams/infraplat
maintainers:
  - name: nr-mdadhich
  - name: nr-mjuvvadi
  - name: shubhamgupta-dev
  - name: msivant
  - name: sbendict
    email: infraplusplatform@newrelic.com
keywords:
  - synthetics
  - synthetics-job-manager
  - node-api-runtime
  - newrelic
