apiVersion: v1
description: A Helm chart to deploy the New Relic Kubernetes Metrics Adapter.
name: newrelic-k8s-metrics-adapter
version: 0.3.1
appVersion: 0.2.0
home: https://hub.docker.com/r/newrelic/newrelic-k8s-metrics-adapter
sources:
  - https://github.com/newrelic/newrelic-k8s-metrics-adapter
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: alvarocabanas
  - name: carlossscastro
  - name: gsanchezgavier
  - name: kang-makes
  - name: paologallinaharbur
  - name: roobre
keywords:
  - infrastructure
  - newrelic
  - monitoring
