apiVersion: v1
description: A Helm chart to deploy the New Relic Php Agent APM.
name: apm-php-agent
version: 1.0.0
appVersion: 1.0.0
home: https://hub.docker.com/r/newrelic/php-daemon
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: gsanchezgavier
  - name: paologallinaharbur
  - name: arvdias
keywords:
  - newrelic
  - apm
  - php
