global:
  cluster: sa-cluster
  licenseKey: test

super-agent-deployment:
  config:
auth:
  # There is no way to test the auth flow for now. Tests get stuck as the pre-install job cannot succeed to create a new system identity.
  # Until we have a better idea or we are able to create a fake oauth server, we have to disable this.
  enabled: false
