apiVersion: v2
name: super-agent-deployment
description: A Helm chart to install New Relic Super agent on Kubernetes

type: application

version: 0.0.29-beta

keywords:
  - newrelic
  - super-agent

maintainers:
  - name: sigilioso
    url: https://github.com/sigilioso
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: kang-makes
    url: https://github.com/kang-makes
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur
