apiVersion: v2
name: synthetics-minion
description: New Relic Synthetics Containerized Private Minion (CPM)
type: application
version: 1.0.56
appVersion: 3.0.72
home: https://github.com/orgs/newrelic/teams/proactive-monitoring
maintainers:
  - name: Philip-R-Beckwith
  - name: sshah-nr
  - name: vkasanneni-nr
  - name: marcusperezNR
  - name: mderemer-nr
  - name: kaschaefer-nr
  - name: sadafarshad
  - name: lromer22
  - name: kondracek-nr
  - name: sidnaiknewrelic
    email: team_proactive-monitoring@newrelic.com
keywords:
  - synthetics
  - synthetics-minion
  - newrelic
