apiVersion: v2
name: synthetics-minion
description: New Relic Synthetics Containerized Private Minion (CPM)
type: application
version: 1.0.46
appVersion: 3.0.57
home: https://github.com/orgs/newrelic/teams/proactive-monitoring
maintainers:
  - name: cleon-nr
    email: team_proactive-monitoring@newrelic.com
  - name: Philip-R-Beckwith
  - name: sshah-nr
  - name: vkasanneni-nr
  - name: marcusperezNR
  - name: sadafarshad
keywords:
  - synthetics
  - synthetics-minion
  - newrelic
