{{- if (include "newrelic-pixie.areValuesValid" .) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "newrelic-pixie.fullname" . }}
  namespace: {{ template "newrelic-pixie.namespace" . }}
  labels:
  {{- include "newrelic-pixie.labels" . | trim | nindent 4}}
  {{- $mergedLabels := include "newrelic-pixie.labels.merged" . }}
  {{- if $mergedLabels }}
    {{- $mergedLabels | fromJson | toYaml | nindent 4 }}
  {{- end }}
  {{- if ((.Values.job).labels) }}
    {{- toYaml .Values.job.labels | nindent 4 }}
  {{- end }}
  {{- if ((.Values.job).annotations) }}
  annotations:
    {{ toYaml .Values.job.annotations | nindent 4 | trim }}
  {{- end }}
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "newrelic-pixie.name" . }}
        release: {{.Release.Name }}
        {{- $mergedPodLabels := include "newrelic-pixie.podLabels.merged" . }}
        {{- if $mergedPodLabels }}
          {{- $mergedPodLabels | fromJson | toYaml | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
          {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- $pullSecrets := include "newrelic-pixie.image.pullSecrets" . }}
      {{- if $pullSecrets }}
      imagePullSecrets:
        {{- $pullSecrets | fromJson | toYaml | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      initContainers:
      - name: cluster-registration-wait
        {{- $registry := include "newrelic-pixie.image.registry" . | default "" }}
        {{- $repo := .Values.clusterRegistrationWaitImage.repository | default "gcr.io/pixie-oss/pixie-dev-public/curl" }}
        {{- if $registry }}
          {{- if or (hasPrefix "gcr.io" $repo) (hasPrefix "docker.io" $repo) }}
            {{- $repo = ($repo | trimPrefix "gcr.io/pixie-oss/pixie-dev-public/" | trimPrefix "docker.io/") }}
          {{- end }}
        image: {{ printf "%s/%s:%s" $registry $repo (.Values.clusterRegistrationWaitImage.tag | default "1.0") | quote }}
        {{- else }}
        image: {{ printf "%s:%s" $repo (.Values.clusterRegistrationWaitImage.tag | default "1.0") | quote }}
        {{- end }}
        {{- $pullPolicy := include "newrelic-pixie.image.pullPolicy" . | default "" }}
        imagePullPolicy: {{ if $pullPolicy }}{{ $pullPolicy | quote }}{{ else }}{{ .Values.clusterRegistrationWaitImage.pullPolicy | default "IfNotPresent" | quote }}{{ end }}
        command: ['sh', '-c', 'set -x;
          URL="https://${SERVICE_NAME}:${SERVICE_PORT}/readyz";
          until [ $(curl -m 0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do
            echo "Waiting for cluster registration. If this takes too long check the vizier-cloud-connector logs."
            sleep 2;
          done;
        ']
        env:
          # The name of the Pixie service which connects to Pixie Cloud for cluster registration. 
        - name: SERVICE_NAME
          value: "vizier-cloud-connector-svc"
        - name: SERVICE_PORT
          value: "50800"
      containers:
      - name: {{ template "newrelic-pixie.name" . }}
        {{- $registry := include "newrelic-pixie.image.registry" . | default "" -}}
        {{- $repo := .Values.image.repository | default "newrelic/newrelic-pixie-integration" -}}
        {{- if $registry -}}
          {{- if hasPrefix "docker.io" $repo }}
            {{- $repo = ($repo | trimPrefix "docker.io/") }}
          {{- end }}
        image: "{{ $registry }}/{{ $repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- else }}
        image: "{{ $repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- end }}
        {{- $pullPolicy := include "newrelic-pixie.image.pullPolicy" . | default "" }}
        imagePullPolicy: "{{ if $pullPolicy }}{{ $pullPolicy }}{{ else }}{{ .Values.image.pullPolicy | default "IfNotPresent" }}{{ end }}"
        {{- $containerSecurityContext := include "newrelic-pixie.containerSecurityContext" . }}
        {{- if $containerSecurityContext }}
        securityContext:
          {{- $containerSecurityContext | fromJson | toYaml | nindent 10 }}
        {{- end }}
        env:
        - name: CLUSTER_NAME
          value: {{ template "newrelic-pixie.cluster" . }}
        - name: NR_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              {{- if (include "newrelic-pixie.licenseKey" .) }}
              name: {{ template "newrelic-pixie.fullname" . }}-secrets
              key: newrelicLicenseKey
              {{- else }}
              name: {{ include "newrelic-pixie.customSecretName" . }}
              key: {{ include "newrelic-pixie.customSecretLicenseKey" . }}
              {{- end }}
        - name: PIXIE_API_KEY
          valueFrom:
            secretKeyRef:
              {{- if (include "newrelic-pixie.apiKey" .) }}
              name: {{ template "newrelic-pixie.fullname" . }}-secrets
              key: pixieApiKey
              {{- else }}
              name: {{ include "newrelic-pixie.customSecretApiKeyName" . }}
              key: {{ include "newrelic-pixie.customSecretApiKeyKey" . }}
          {{- end }}
        - name: PIXIE_CLUSTER_ID
          {{- if .Values.clusterId }}
          value: {{ .Values.clusterId -}}
          {{- else }}
          valueFrom:
            secretKeyRef:
              key: cluster-id
              name: pl-cluster-secrets
          {{- end }}
        {{- if .Values.verbose }}
        - name: VERBOSE
          value: "true"
        {{- end }}
        {{- if (include "newrelic-pixie.lowDataMode" .) }}
        - name: COLLECT_INTERVAL_SEC
          value: "15"
        - name: HTTP_SPAN_LIMIT
          value: "750"
        - name: DB_SPAN_LIMIT
          value: "250"
        {{- else }}
        - name: COLLECT_INTERVAL_SEC
          value: "10"
        - name: HTTP_SPAN_LIMIT
          value: "1500"
        - name: DB_SPAN_LIMIT
          value: "500"
        {{- end }}
        {{- if (include "newrelic-pixie.nrStaging" .) }}
        - name: NR_OTLP_HOST
          value: "staging-otlp.nr-data.net:4317"
        {{- end }}
        {{- if or .Values.endpoint (include "newrelic-pixie.nrStaging" .) }}
        - name: PIXIE_ENDPOINT
          {{- if .Values.endpoint }}
          value: {{ .Values.endpoint | quote }}
          {{- else }}
          value: "staging.withpixie.dev:443"
          {{- end }}
        {{- end }}
        {{- $proxy := include "newrelic-pixie.proxy" . }}
        {{- if $proxy }}
        - name: HTTP_PROXY
          value: {{ $proxy | quote }}
        - name: HTTPS_PROXY
          value: {{ $proxy | quote }}
        {{- end }}
        {{- if .Values.excludePodsRegex }}
        - name: EXCLUDE_PODS_REGEX
          value: {{ .Values.excludePodsRegex | quote }}
        {{- end }}
        {{- if .Values.excludeNamespacesRegex }}
        - name: EXCLUDE_NAMESPACES_REGEX
          value: {{ .Values.excludeNamespacesRegex | quote }}
        {{- end }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      {{- if or .Values.customScriptsConfigMap .Values.customScripts }}
        volumeMounts:
          - name: scripts
            mountPath: "/scripts"
            readOnly: true
      volumes:
        - name: scripts
          configMap:
            {{- if .Values.customScriptsConfigMap }}
            name: {{ .Values.customScriptsConfigMap }}
            {{- else }}
            name: {{ template "newrelic-pixie.fullname" . }}-scripts
            {{- end}}
      {{- end }}
      {{- $priorityClassName := include "newrelic-pixie.priorityClassName" . }}
      {{- if $priorityClassName }}
      priorityClassName: {{ $priorityClassName }}
      {{- end }}
      {{- $nodeSelector := include "newrelic-pixie.nodeSelector" . }}
      {{- if $nodeSelector }}
      nodeSelector:
        {{- $nodeSelector | fromJson | toYaml | nindent 8 }}
      {{- end }}
      {{- $tolerations := include "newrelic-pixie.tolerations" . }}
      {{- if $tolerations }}
      tolerations:
        {{- $tolerations | fromJson | toYaml | nindent 8 }}
      {{- end }}
      {{- $affinity := include "newrelic-pixie.affinity" . }}
      {{- if $affinity }}
      affinity:
        {{- $affinity | fromJson | toYaml | nindent 8 }}
      {{- end }}
      {{- $dnsConfig := include "newrelic-pixie.dnsConfig" . }}
      {{- if $dnsConfig }}
      dnsConfig:
        {{- $dnsConfig | fromJson | toYaml | nindent 8 }}
      {{- end }}
      {{- $hostNetwork := include "newrelic-pixie.hostNetwork" . }}
      {{- if $hostNetwork }}
      hostNetwork: {{ $hostNetwork }}
      {{- end }}
      {{- $podSecurityContext := include "newrelic-pixie.podSecurityContext" . }}
      {{- if $podSecurityContext }}
      securityContext:
        {{- $podSecurityContext | fromJson | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
