apiVersion: v1
appVersion: 1.1.0
description: A Helm chart to deploy the New Relic Kube Events
name: nri-kube-events
version: 1.0.0
engine: gotpl
home: https://docs.newrelic.com/docs/integrations/kubernetes-integration/kubernetes-events/install-kubernetes-events-integration
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
keywords:
  - events
  - newrelic
  - monitoring
maintainers:
- name: douglascamata
- name: jorikvdwerf
