apiVersion: v2
name: synthetics-job-manager
description: New Relic Synthetics Containerized Job Manager
type: application
version: 3.0.9
appVersion: release-428
home: https://github.com/orgs/newrelic/teams/proactive-monitoring
maintainers:
  - name: kaschaefer-nr
  - name: sidnaiknewrelic
  - name: Philip-R-Beckwith
  - name: sshah-nr
  - name: marcusperezNR
  - name: sadafarshad
  - name: kondracek-nr
  - name: mfarhan-nr
  - name: schakraborty-nr
  - name: shashank-srirangam
  - name: nr-mdadhich
  - name: nr-amrendrasingh
    email: team_proactive-monitoring@newrelic.com
keywords:
  - synthetics
  - synthetics-job-manager
  - job-manager
  - newrelic
dependencies:
  - name: ping-runtime
    version: 1.0.24
    condition: ping-runtime.enabled
  - name: node-api-runtime
    version: 1.0.38
    condition: node-api-runtime.enabled
  - name: node-browser-runtime
    version: 2.0.5
    condition: node-browser-runtime.enabled
