apiVersion: v2
name: synthetics-job-manager
description: New Relic Synthetics Containerized Job Manager
type: application
version: 1.0.0
appVersion: latest # TODO - This should probably specify an actual release version
home: https://github.com/orgs/newrelic/teams/proactive-monitoring
maintainers:
  - name: Philip-R-Beckwith
  - name: sshah-nr
  - name: vkasanneni-nr
  - name: marcusperezNR
  - name: mderemer-nr
  - name: kaschaefer-nr
  - name: sadafarshad
  - name: lromer22
    email: team_proactive-monitoring@newrelic.com
keywords:
  - synthetics
  - synthetics-job-manager
  - newrelic
dependencies:
  - name: ping-runtime
    condition: ping-runtime.enabled
  - name: node-api-runtime
    condition: node-api-runtime.enabled
  - name: node-browser-runtime
    condition: node-browser-runtime.enabled
