apiVersion: v2
name: synthetics-job-manager
description: New Relic Synthetics Containerized Job Manager
type: application
version: 1.0.58
appVersion: release-332
home: https://github.com/orgs/newrelic/teams/proactive-monitoring
maintainers:
  - name: Philip-R-Beckwith
  - name: sshah-nr
  - name: vkasanneni-nr
  - name: marcusperezNR
  - name: mderemer-nr
  - name: kaschaefer-nr
  - name: sadafarshad
  - name: lromer22
  - name: kondracek-nr
  - name: sidnaiknewrelic
email: team_proactive-monitoring@newrelic.com
keywords:
  - synthetics
  - synthetics-job-manager
  - job-manager
  - newrelic
dependencies:
  - name: ping-runtime
version: 1.0.16
condition: ping-runtime.enabled
  - name: node-api-runtime
version: 1.0.27
condition: node-api-runtime.enabled
  - name: node-browser-runtime
version: 1.0.35
condition: node-browser-runtime.enabled
