apiVersion: v2
name: otel-k8s-prometheus
description: A chart to scrape prometheus endpoints using the opentelemetry collector
maintainers:
  - name: roobre
type: application

version: 0.1.0
appVersion: "0.38.0"
