global:
  licenseKey: 1234567890abcdef1234567890abcdef12345678
  cluster: test-cluster

infrastructure:
  enabled: true

prometheus:
  enabled: true

webhook:
  enabled: true

# shorten the name of the webhook, because it was reaching its limit
nri-metadata-injection:
  fullnameOverride: nri-webhook

ksm:
  enabled: true

kubeEvents:
  enabled: true

logging:
  enabled: true

newrelic-pixie:
  enabled: true

pixie:
  enabled: true