apiVersion: v1
description: A Helm chart to deploy New Relic Kubernetes Logging as a DaemonSet
name: newrelic-logging
version: 1.6.1
appVersion: 1.8.0
home: https://github.com/newrelic/kubernetes-logging
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: jsubirat
email: logging-team@newrelic.com
  - name: tejunior
  - name: jodstrcil
  - name: edmocosta
  - name: Noly
  - name: danybmx
keywords:
  - logging
  - newrelic
