apiVersion: v1
description: A Helm chart to deploy New Relic Kubernetes Logging as a DaemonSet
name: newrelic-logging
version: 1.2.4
appVersion: 1.3.0
home: https://github.com/newrelic/kubernetes-logging
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: bmcfeely
    email: logging-team@newrelic.com
  - name: matildasmeds
  - name: tejunior
  - name: jsubirat
keywords:
  - logging
  - newrelic
