apiVersion: v1
description: A Helm chart to deploy New Relic Kubernetes Logging as a DaemonSet
name: newrelic-logging
version: 1.4.2
appVersion: 1.4.3
home: https://github.com/newrelic/kubernetes-logging
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: jsubirat
    email: logging-team@newrelic.com
  - name: matildasmeds
  - name: tejunior
keywords:
  - logging
  - newrelic
