apiVersion: v2
description: A Helm chart to deploy New Relic Kubernetes Logging as a DaemonSet, supporting both Linux and Windows nodes and containers
name: newrelic-logging
version: 1.21.2
appVersion: 1.19.2
home: https://github.com/newrelic/kubernetes-logging
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: jsubirat
    email: logging-team@newrelic.com
  - name: danybmx
  - name: sdaubin
keywords:
  - logging
  - newrelic
dependencies:
  - name: common-library
    version: 1.1.1
    repository: "https://helm-charts.newrelic.com"
