apiVersion: v1
description: A Helm chart to deploy New Relic Kubernetes Logging as a DaemonSet
name: newrelic-logging
version: 1.0.4
appVersion: 1.2.1
home: https://github.com/newrelic/kubernetes-logging
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: bmcfeely
email: logging-team@newrelic.com
keywords:
  - logging
  - newrelic
