apiVersion: v2
name: super-agent
description: Bootstraps New Relic' Super Agent

type: application
version: 0.0.8-beta

dependencies:
  - name: flux2
repository: https://fluxcd-community.github.io/helm-charts
version: 2.12.2
condition: flux2.enabled
  - name: common-library
version: 1.1.1
repository: https://helm-charts.newrelic.com
  - name: super-agent-deployment
version: 0.0.16-beta
repository: https://helm-charts.newrelic.com
condition: super-agent-deployment.enabled

keywords:
  - newrelic
  - super-agent

maintainers:
  - name: sigilioso
url: https://github.com/sigilioso
  - name: gsanchezgavier
url: https://github.com/gsanchezgavier
  - name: kang-makes
url: https://github.com/kang-makes
  - name: marcsanmi
url: https://github.com/marcsanmi
  - name: paologallinaharbur
url: https://github.com/paologallinaharbur
