{{- if .Values.jobManager.leases.enabled -}}
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: {{ include "job-manager.fullname" . }}-runtime-pruning
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "job-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: lease
    newrelic.com/lease-type: runtime-pruning
spec:
  holderIdentity: ""
  leaseDurationSeconds: {{ .Values.jobManager.leases.leaseDurationSeconds }}
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: {{ include "job-manager.fullname" . }}-service-setup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "job-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: lease
    newrelic.com/lease-type: service-setup
spec:
  holderIdentity: ""
  leaseDurationSeconds: {{ .Values.jobManager.leases.leaseDurationSeconds }}
{{- end }}
