{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "job-manager.fullname" . }}-runtime
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "job-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "job-manager.fullname" . }}-runtime
subjects:
  - kind: ServiceAccount
    name: {{ include "job-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
