# Job Manager Service Account
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "job-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "job-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
# Runtime Pods Service Account
{{- if .Values.runtimePodServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "job-manager.runtimePodServiceAccountName" . }}
  namespace: {{ .Values.runtimePodNetworkPolicy.runtimePodNamespace | default .Release.Namespace }}
  labels:
    {{- include "job-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime-pod-service-account
  {{- with .Values.runtimePodServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
