{{- if (include "nri-statsd.areValuesValid" .) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nri-statsd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "nri-statsd.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nri-statsd.name" . }}
  template:
    metadata:
      labels:
{{ include "nri-statsd.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "nri-statsd.serviceAccountName" . }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: nri-statsd
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - containerPort: {{ .Values.statsdPort }}
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: TAGS
        {{- if $.Values.metricTags }}
            value: clusterName:{{ include "nri-statsd.cluster" .}} {{ include "nri-statsd.statsdMetricTags" . }}
        {{- else }}
            value: clusterName:{{ include "nri-statsd.cluster" .}}
        {{- end }}
        {{- if and (not .Values.enableConfigmap) (or "$.Values.nri-statsd.insightsKey" (and "$.Values.nri-statsd.customSecretName" "$.Values.nri-statsd.customSecretInsightsKey")) }}
          - name: NR_API_KEY
            valueFrom:
              secretKeyRef:
                {{- if (include "nri-statsd.insightsKey" .) }}
                name: {{ template "nri-statsd.fullname" . }}-config
                key: insights
                {{- else }}
                name: {{ include "nri-statsd.customSecretName" . }}
                key: {{ include "nri-statsd.customSecretInsightsKey" . }}
                {{- end }}
          - name: NR_ACCOUNT_ID
            value: {{ .Values.accountId | quote }}
        {{- end }}
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        {{- if .Values.enableConfigmap }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/opt/newrelic/
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "nri-statsd.fullname" . }}-config
      {{- end }}
      {{- if $.Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      {{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
{{- end }}
