apiVersion: v2
name: serverless-job-manager
description: New Relic Serverless Job Manager for K8s-based Serverless Location Deployment
type: application
version: 1.0.0
appVersion: release-1
home: https://github.com/orgs/newrelic/teams/proactive-monitoring
maintainers:
  - name: kaschaefer-nr
  - name: sidnaiknewrelic
  - name: Philip-R-Beckwith
  - name: sshah-nr
  - name: marcusperezNR
  - name: sadafarshad
  - name: kondracek-nr
  - name: mfarhan-nr
  - name: schakraborty-nr
  - name: shashank-srirangam
  - name: nr-mdadhich
  - name: nr-mjuvvadi
  - name: nr-amrendrasingh
  - name: syeddula-279
    email: team_proactive-monitoring@newrelic.com
keywords:
  - serverless
  - serverless-job-manager
  - job-manager
  - newrelic
  - kubernetes
dependencies:
  - name: node-api-runtime
    version: 1.0.47
    condition: node-api-runtime.enabled
  - name: node-browser-runtime
    version: 2.0.12
    condition: node-browser-runtime.enabled