{{- if .Values.kubelet.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-kubelet
  namespace: {{ .Release.Namespace }}
data:
  nri-kubernetes.yml: |
{{- (merge .Values.common.config (include "newrelic.integrationConfigDefaults" . | fromYaml)) | toYaml | nindent 4 }}
kubelet:
  enabled: true
  {{- if .Values.kubelet.config }}
  {{- toYaml .Values.kubelet.config | nindent 6 }}
  {{- end }}
{{- end }}
