{{- if (.Values.kubelet.enabled) }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-kubelet
  {{- with .Values.kubelet.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.updateStrategy }}
  updateStrategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
matchLabels:
  {{- include "newrelic.selectorLabels" . | nindent 6 }}
  app.kubernetes.io/component: kubelet
  template:
metadata:
  annotations:
checksum/nri-kubernetes: {{ include (print $.Template.BasePath "/kubelet/configmap.yaml") . | sha256sum }}
{{- if not (include "newrelic.licenseCustomSecretName" .) }}
checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- end }}
{{- if .Values.common.agentConfig }}
checksum/agent-config: {{ include (print $.Template.BasePath "/agent-configmap.yaml") . | sha256sum }}
{{- end }}
{{- if .Values.integrations_config }}
checksum/integrations_config: {{ include (print $.Template.BasePath "/kubelet/integrations-configmap.yaml") . | sha256sum }}
{{- end }}
{{- with .Values.podAnnotations }}
{{- toYaml . | nindent 8 }}
{{- end }}
  labels:
{{- include "newrelic.selectorLabels" . | nindent 8 }}
app.kubernetes.io/component: kubelet
{{- with .Values.podLabels }}
  {{- toYaml . | nindent 8 }}
{{- end }}
mode: {{ include "newrelic.mode" . }}
spec:
  {{- with .Values.images.pullSecrets }}
  imagePullSecrets:
{{- toYaml . | nindent 8 }}
  {{- end }}
  serviceAccountName: {{ template "newrelic.serviceAccountName" . }}
  containers:
- name: kubelet
  image: "{{ .Values.images.integration.registry }}/{{ .Values.images.integration.repository }}:{{ .Values.images.integration.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.images.integration.pullPolicy }}
  securityContext:
{{- toYaml .Values.securityContext | nindent 12 }}
  env:
- name: "NRI_KUBERNETES_HTTPSERVERPORT"
  value: "8003"
- name: "NRI_KUBERNETES_CLUSTERNAME"
  value: {{ include "newrelic.cluster" . | required "cluster name must be set" }}
{{- if .Values.verboseLog }}
- name: NRI_KUBERNETES_VERBOSE
  value: "1"
{{- end }}
- name: "NRI_KUBERNETES_NODENAME"
  valueFrom:
fieldRef:
  apiVersion: "v1"
  fieldPath: "spec.nodeName"
# Required to connect to the kubelet
- name: "NRI_KUBERNETES_NODEIP"
  valueFrom:
fieldRef:
  apiVersion: "v1"
  fieldPath: "status.hostIP"
{{- with .Values.kubelet.extraEnv }}
{{- toYaml . | nindent 12 }}
{{- end }}
  {{- with .Values.kubelet.extraEnvFrom }}
  envFrom: {{ toYaml . | nindent 12 }}
  {{- end }}
  volumeMounts:
- name: nri-kubernetes-config
  mountPath: /etc/newrelic-infra/nri-kubernetes.yml
  subPath: nri-kubernetes.yml
{{- with .Values.kubelet.extraVolumeMounts }}
{{- toYaml . | nindent 12 }}
{{- end }}
  {{- with .Values.kubelet.resources }}
  resources: {{ toYaml . | nindent 12 }}
  {{- end }}
- name: agent
  image: "{{ .Values.images.agent.registry }}/{{ .Values.images.agent.repository }}:{{ .Values.images.agent.tag }}"
  command: [ "/sbin/tini", "--", "/usr/bin/newrelic-infra" ]
  imagePullPolicy: {{ .Values.images.agent.pullPolicy }}
  securityContext:
  {{- if .Values.privileged }}
privileged: true
readOnlyRootFilesystem: true
  {{- else }}
{{- toYaml .Values.securityContext | nindent 12 }}
  {{- end }}
  ports:
- containerPort: 8003
  env:
- name: "NRIA_OVERRIDE_HOSTNAME_SHORT"
  valueFrom:
fieldRef:
  apiVersion: "v1"
  fieldPath: "spec.nodeName"
- name: "NRIA_FEATURES"
  value: "docker_enabled:false"
- name: "NRIA_HTTP_SERVER_ENABLED"
  value: "true"
- name: "NRIA_HTTP_SERVER_PORT"
  value: "8003"
- name: NRIA_LICENSE_KEY
  valueFrom:
secretKeyRef:
  name: {{ include "newrelic.licenseSecretName" . | required "licenseKey or customSecretName and customSecretLicenseKey must be set" }}
  key: {{ include "newrelic.licenseSecretKey" . | required "licenseKey or customSecretName and customSecretLicenseKey must be set" }}
{{- /* Check if enableProcessMetrics is present in the map */}}
{{- if .Values.enableProcessMetrics | kindIs "bool" }}
- name: "NRIA_ENABLE_PROCESS_METRICS"
  value: {{ .Values.enableProcessMetrics | quote }}
{{- end }}
{{- if (include "newrelic.nrStaging" .) }}
- name: "NRIA_STAGING"
  value: "true"
{{- end }}
- name: "NRI_KUBERNETES_NODE_NAME"
  valueFrom:
fieldRef:
  apiVersion: "v1"
  fieldPath: "spec.nodeName"
{{- if .Values.useNodeNameAsDisplayName }}
- name: "NRIA_DISPLAY_NAME"
{{- if .Values.prefixDisplayNameWithCluster }}
  value: "{{ include "newrelic.cluster" . }}:$(NRI_KUBERNETES_NODE_NAME)"
{{- else }}
  valueFrom:
fieldRef:
  apiVersion: "v1"
  fieldPath: "spec.nodeName"
{{- end }}
{{- end }}
{{- if (include "newrelic.customAttributes" .) }}
- name: "NRIA_CUSTOM_ATTRIBUTES"
  value: >-
{{- include "newrelic.customAttributes" . | nindent 16 }}
{{- end }}
{{- if .Values.verboseLog }}
- name: NRIA_VERBOSE
  value: "1"
{{- end }}
{{- with .Values.logFile }}
- name: NRIA_LOG_FILE
  value: {{ . }}
{{- end }}
{{- if not .Values.privileged }}
- name: "NRIA_OVERRIDE_HOST_ROOT"
  value: ""
- name: "NRIA_IS_SECURE_FORWARD_ONLY"
  value: "true"
{{- end }}
{{- with .Values.kubelet.extraEnv }}
{{- toYaml . | nindent 12 }}
{{- end }}
  {{- with .Values.kubelet.extraEnvFrom }}
  envFrom: {{ toYaml . | nindent 12 }}
  {{- end }}
  volumeMounts:
{{- if .Values.common.agentConfig }}
- name: config
  mountPath: /etc/newrelic-infra.yml
  subPath: newrelic-infra.yml
{{- end }}
{{- if .Values.integrations_config }}
- name: nri-integrations-cfg-volume
  mountPath: /etc/newrelic-infra/integrations.d/
{{- end }}
{{- if .Values.privileged }}
- name: dev
  mountPath: /dev
- name: host-docker-socket
  mountPath: /var/run/docker.sock
- name: log
  mountPath: /var/log
- name: host-volume
  mountPath: /host
  readOnly: true
{{- end }}
- mountPath: /var/db/newrelic-infra/data
  name: agent-tmpfs-data
- mountPath: /var/db/newrelic-infra/user_data
  name: agent-tmpfs-user-data
- mountPath: /tmp
  name: agent-tmpfs-tmp
{{- with .Values.kubelet.extraVolumeMounts }}
{{- toYaml . | nindent 12 }}
{{- end }}
  {{- with .Values.kubelet.resources }}
  resources: {{ toYaml . | nindent 12 }}
  {{- end }}
  volumes:
{{- if .Values.privileged }}
- name: dev
  hostPath:
path: /dev
- name: host-docker-socket
  hostPath:
path: /var/run/docker.sock
- name: log
  hostPath:
path: /var/log
- name: host-volume
  hostPath:
path: /
{{- end }}
- name: agent-tmpfs-data
  emptyDir: {}
- name: agent-tmpfs-user-data
  emptyDir: {}
- name: agent-tmpfs-tmp
  emptyDir: {}
- name: nri-kubernetes-config
  configMap:
name: {{ template "newrelic.fullname" . }}-kubelet
items:
  - key: nri-kubernetes.yml
path: nri-kubernetes.yml
{{- if .Values.common.agentConfig }}
- name: config
  configMap:
name: {{ template "newrelic.fullname" . }}-agent
items:
  - key: newrelic-infra.yml
path: newrelic-infra.yml
{{- end }}
{{- if .Values.integrations_config }}
- name: nri-integrations-cfg-volume
  configMap:
name: {{ template "newrelic.fullname" . }}-integrations-cfg
{{- end }}
{{- with .Values.kubelet.extraVolumes }}
{{- toYaml . | nindent 8 }}
{{- end }}
  {{- with .Values.priorityClassName }}
  priorityClassName: {{ . }}
  {{- end }}
  {{- if .Values.kubelet.affinity.nodeAffinity }}
  affinity:
nodeAffinity:
  {{- .Values.kubelet.affinity.nodeAffinity | toYaml | nindent 10 }}
  {{- else if include "newrelic.fargate" . }}
  affinity:
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
  - matchExpressions:
  - key: eks.amazonaws.com/compute-type
operator: NotIn
values:
  - fargate
  {{- end }}
  {{- with .Values.kubelet.tolerations }}
  tolerations:
{{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.kubelet.nodeSelector }}
  nodeSelector:
{{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
