{{- if (.Values.serverless.userDefinedVariables).userDefinedFile -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "serverless-job-manager.configMapName" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "serverless-job-manager.labels" . | nindent 4 }}
    {{- with .Values.labels -}}
      {{ toYaml . | nindent 4 }}
    {{- end }}
data:
  user_defined_variables.json: {{ .Values.serverless.userDefinedVariables.userDefinedFile | quote }}
{{- end -}}