{{- if include "newrelic.common.serviceAccount.create" . }}
---
# ClusterRoleBinding for StatefulSet collector
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nrKubernetesOtel.deployment.serviceAccountName" . }}
  labels:
{{- include "newrelic.common.labels" . | nindent 4 }}
app.kubernetes.io/component: statefulset-collector
subjects:
  - kind: ServiceAccount
    name: {{ include "nrKubernetesOtel.deployment.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "nrKubernetesOtel.deployment.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRoleBinding for DaemonSet collector
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nrKubernetesOtel.daemonset.serviceAccountName" . }}
  labels:
{{- include "newrelic.common.labels" . | nindent 4 }}
app.kubernetes.io/component: daemonset-collector
subjects:
  - kind: ServiceAccount
    name: {{ include "nrKubernetesOtel.daemonset.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "nrKubernetesOtel.daemonset.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
