apiVersion: v2
name: node-browser-runtime
description: New Relic Synthetics Browser Runtime
type: application
version: 1.0.10
appVersion: 1.1.68
home: https://github.com/orgs/newrelic/teams/proactive-monitoring
maintainers:
  - name: Philip-R-Beckwith
  - name: sshah-nr
  - name: vkasanneni-nr
  - name: marcusperezNR
  - name: mderemer-nr
  - name: kaschaefer-nr
  - name: sadafarshad
  - name: lromer22
  - name: kondracek-nr
email: team_proactive-monitoring@newrelic.com
keywords:
  - synthetics
  - synthetics-job-manager
  - node-browser-runtime
  - newrelic
