apiVersion: v2
name: newrelic-infrastructure
description: A Helm chart to deploy the New Relic Kubernetes monitoring solution
version: 3.0.0
appVersion: 3.0.0
home: https://hub.docker.com/r/newrelic/nri-kubernetes/
sources:
  - https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-infrastructure
icon: https://newrelic.com/themes/custom/curio/assets/mediakit/NR_logo_Horizontal.svg
maintainers:
  - name: alvarocabanas
  - name: carlossscastro
  - name: gsanchezgavier
  - name: kang-makes
  - name: paologallinaharbur
  - name: roobre
keywords:
  - infrastructure
  - newrelic
  - monitoring
