apiVersion: v2
name: super-agent-deployment
description: A Helm chart to install New Relic Super agent on Kubernetes

type: application
version: 0.0.6-beta
appVersion: nightly  # TODO: Change this with a proper version of the image.

dependencies:
  - name: common-library
    version: 1.1.1
    repository: https://helm-charts.newrelic.com

keywords:
  - newrelic
  - super-agent

maintainers:
  - name: sigilioso
    url: https://github.com/sigilioso
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: kang-makes
    url: https://github.com/kang-makes
  - name: marcsanmi
    url: https://github.com/marcsanmi
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur
