{{- if include "newrelic.compatibility.ksm.enabled" .  -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-ksm
  namespace: {{ .Release.Namespace }}
data:
  nri-kubernetes.yml: |-
{{- (merge .Values.common.config (include "newrelic.integrationConfigDefaults" . | fromYaml)) | toYaml | nindent 4 }}
ksm:
  {{- /* Notice that new values takes precedence since they have no default and the user need to set them up specifically*/ -}}
  {{- mustMergeOverwrite (include "newrelic.compatibility.ksm.legacyData" . | fromYaml) .Values.ksm.config | toYaml | nindent 6 -}}
{{- end -}}
