{{- if .Values.ksm.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-ksm
data:
  nri-kubernetes-config.yml: |
{{- .Values.common.config | toYaml | nindent 4 }}
ksm:
  enabled: true
  {{- with .Values.ksm.config }}
  {{- . | toYaml | nindent 6 }}
  {{- end }}
{{- end }}
