{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "newrelic-k8s-metrics-adapter.fullname" . }}-apiservice-patch
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "newrelic-k8s-metrics-adapter.name" $ }}
{{ include "newrelic-k8s-metrics-adapter.labels" $ | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "newrelic-k8s-metrics-adapter.fullname" . }}-apiservice-patch
      labels:
        app: {{ template "newrelic-k8s-metrics-adapter.name" $ }}
{{ include "newrelic-k8s-metrics-adapter.labels" $ | indent 8 }}
    spec:
      {{- if .Values.apiServicePatchJob.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.apiServicePatchJob.image.pullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: patch
          image: {{ .Values.apiServicePatchJob.image.repository }}:{{ .Values.apiServicePatchJob.image.tag }}
          imagePullPolicy: {{ .Values.apiServicePatchJob.image.pullPolicy }}
          args:
            - patch
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ template "newrelic-k8s-metrics-adapter.fullname" . }}-apiservice
            - --apiservice-name=v1beta1.external.metrics.k8s.io
          {{- if .Values.apiServicePatchJob.image.volumeMounts }}
          volumeMounts:
          {{- include "tplvalues.render" ( dict "value" .Values.apiServicePatchJob.image.volumeMounts "context" $ ) | nindent 10 }}
          {{- end }}
      {{- if .Values.apiServicePatchJob.image.volumes }}
      volumes:
      {{- include "tplvalues.render" ( dict "value" .Values.apiServicePatchJob.image.volumes "context" $ ) | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "newrelic-k8s-metrics-adapter.fullname" . }}-apiservice
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
