{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "newrelic-k8s-metrics-adapter.fullname" . }}-apiservice
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "newrelic-k8s-metrics-adapter.name" $ }}
{{ include "newrelic-k8s-metrics-adapter.labels" $ | indent 4 }}
{{- end }}
