apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "nri-metadata-injection.fullname" . }}
{{- if .Values.certManager.enabled }}
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ printf "%s/%s-root-cert" .Release.Namespace (include "nri-metadata-injection.fullname" .) | quote }}
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-root-cert" .Release.Namespace (include "nri-metadata-injection.fullname" .) | quote }}
{{- end }}
  labels:
    {{- include "nri-metadata-injection.labels" . | nindent 4 }}
webhooks:
- name: metadata-injection.newrelic.com
  clientConfig:
    service:
      name: {{ template "nri-metadata-injection.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: "/mutate"
{{- if not .Values.certManager.enabled }}
    caBundle: ""
{{- end }}
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
{{- if .Values.injectOnlyLabeledNamespaces }}
  namespaceSelector:
    matchLabels:
      newrelic-metadata-injection: enabled
{{- end }}
  failurePolicy: Ignore
{{ if (gt (.Capabilities.KubeVersion.Minor | atoi) 14) }}
  timeoutSeconds: {{ .Values.timeoutSeconds }}
{{- end }}
