apiVersion: v1
description: A Helm chart to deploy the New Relic Infrastructure Agent as a DaemonSet
name: newrelic-infrastructure
version: 2.0.1
appVersion: 2.0.1
home: https://hub.docker.com/r/newrelic/infrastructure-k8s/
source:
  - https://github.com/kubernetes/kubernetes/tree/master/examples/newrelic-infrastructure
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: rk295
email: robin@kearney.co.uk
  - name: jfjoly
email: jjoly@newrelic.com
  - name: areina
  - name: douglascamata
  - name: jorik
  - name: alejandrodnm
  - name: rk295
  - name: bpschmitt
keywords:
  - infrastructure
  - newrelic
  - monitoring
