apiVersion: v1
description: A Helm chart to deploy the New Relic Infrastructure Agent as a DaemonSet
name: newrelic-infrastructure
version: 2.10.0
appVersion: 2.11.0
home: https://hub.docker.com/r/newrelic/infrastructure-k8s/
sources:
  - https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-infrastructure
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: alvarocabanas
  - name: carlossscastro
  - name: gsanchezgavier
  - name: kang-makes
  - name: paologallinaharbur
  - name: roobre
keywords:
  - infrastructure
  - newrelic
  - monitoring
