apiVersion: v1
description: A Helm chart for the New Relic Pixie integration.
name: newrelic-pixie
version: 2.1.4
appVersion: 2.1.4
home: https://hub.docker.com/u/newrelic
sources:
  - https://github.com/newrelic/
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: nserrino
  - name: philkuz
  - name: htroisi
  - name: vuqtran88
keywords:
  - newrelic
  - pixie
  - monitoring
