apiVersion: v1
description: A Helm chart for the New Relic Pixie integration.
name: newrelic-pixie
version: 2.0.0
appVersion: 2.0.0
home: https://hub.docker.com/u/newrelic
sources:
  - https://github.com/newrelic/
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: alvarocabanas
  - name: carlossscastro
  - name: gsanchezgavier
  - name: kang-makes
  - name: paologallinaharbur
  - name: roobre
keywords:
  - newrelic
  - pixie
  - monitoring
