apiVersion: v1
description: A Helm chart for the New Relic Pixie integration.
name: newrelic-pixie

version: 2.1.1
appVersion: 2.1.3

home: https://hub.docker.com/u/newrelic
sources:
  - https://github.com/newrelic/
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: nserrino
  - name: philkuz
  - name: htroisi
  - name: juanjjaramillo
  - name: svetlanabrennan
  - name: nrepai
  - name: csongnr
  - name: xqi-nr
keywords:
  - newrelic
  - pixie
  - monitoring
