apiVersion: v1
description: A Helm chart for the New Relic Pixie integration.
name: newrelic-pixie
version: 1.1.2
appVersion: 1.1.0
home: https://hub.docker.com/u/newrelic
sources:
  - https://github.com/newrelic/
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: douglascamata
keywords:
  - newrelic
  - pixie
  - monitoring
