# -- Name of the Kubernetes cluster monitored. Can be configured also with `global.cluster`
cluster: ""

# -- New Relic license key. Can be configured also with `global.licenseKey`
licenseKey: ""

# -- Pixie API key (separate from New Relic licenseKey). Must be obtained from work.withpixie.ai. Can be configured also with `global.apiKey`
apiKey: ""

# -- Pixie Cluster ID
clusterId: ""

# -- Pixie endpoint URL
endpoint: ""

# -- Name of existing Secret containing New Relic license key. Can be configured also with `global.customSecretName`
customSecretName: ""
# -- Key in Secret containing New Relic license key. Can be configured also with `global.customSecretLicenseKey`
customSecretLicenseKey: ""
# -- Name of existing Secret containing Pixie API key
customSecretApiKeyName: ""
# -- Key in Secret containing Pixie API key
customSecretApiKeyKey: ""

# -- Image used to wait for Pixie cluster registration
# @default -- See `values.yaml`
clusterRegistrationWaitImage:
  repository: gcr.io/pixie-oss/pixie-dev-public/curl
  tag: "1.0"
  # -- Image pull policy. Can be configured also with `global.images.pullPolicy`. Defaults to IfNotPresent
  pullPolicy: ""

# -- Image for New Relic Pixie integration
# @default -- See `values.yaml`
image:
  repository: newrelic/newrelic-pixie-integration
  tag: ""
  # -- Image pull policy. Can be configured also with `global.images.pullPolicy`. Defaults to IfNotPresent
  pullPolicy: ""
  # -- Image pull secrets. Can be configured also with `global.images.pullSecrets`
  pullSecrets: []
  # - name: regsecret

# -- Resources for the integration container
# @default -- See `values.yaml`
resources:
  limits:
    memory: 250M
  requests:
    cpu: 100m
    memory: 250M

# -- Annotations to add to the pod.
podAnnotations: {}
# -- Additional labels for chart pods
podLabels: {}

job:
  # job.annotations -- Annotations to add to the Job.
  annotations: {}
  # job.labels -- Labels to add to the Job.
  labels: {}

# -- HTTP/HTTPS proxy URL for connectivity. Can be configured also with `global.proxy`
proxy: {}

# -- Node selector for pod scheduling. Can be configured also with `global.nodeSelector`
nodeSelector: {}

# -- Node tolerations for tainted nodes. Can be configured also with `global.tolerations`
tolerations: []

# -- Pod affinity rules. Can be configured also with `global.affinity`
affinity: {}

# -- Custom Pixie scripts
customScripts: {}
# -- Name of existing ConfigMap containing custom scripts
customScriptsConfigMap: ""

# -- Regex pattern to exclude namespaces from monitoring
excludeNamespacesRegex: ""
# -- Regex pattern to exclude pods from monitoring
excludePodsRegex: ""

# -- Enable verbose logging. Can be configured also with `global.verboseLog`
verbose:

# -- Enable New Relic staging endpoints. Can be configured also with `global.nrStaging`
nrStaging:

# -- Enable low data mode for reduced telemetry volume. When enabled, the integration performs heavier sampling on Pixie span data and sets the collect interval to 15 seconds instead of 10 seconds. Can be configured also with `global.lowDataMode`
# @default -- false
lowDataMode:
