# IMPORTANT: The Kubernetes cluster name
# https://docs.newrelic.com/docs/kubernetes-monitoring-integration
# cluster: ""

# The New Relic license key
# licenseKey: ""

# The Pixie API key
# apiKey: ""

# If you already have a secret where the New Relic license key is stored, indicate its name here
# customSecretName:
# The key in the customSecretName secret that contains the New Relic license key
# customSecretLicenseKey:
# If you already have a secret where the Pixie API key is stored, indicate its name here
# customSecretApiKeyName:
# The key in the customSecretApiKeyName secret that contains the Pixie API key
# customSecretApiKeyKey:

image:
  repository: newrelic/newrelic-pixie-integration
  tag: ""
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 250M
  requests:
    cpu: 100m
    memory: 250M
