{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "nri-metadata-injection.fullname" . }}-admission-create
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "nri-metadata-injection.name" $ }}-admission-create
{{ include "nri-metadata-injection.labels" $ | indent 4 }}
spec:
  template:
    metadata:
      name:  {{ template "nri-metadata-injection.fullname" . }}-admission-create
      labels:
        app: {{ template "nri-metadata-injection.name" $ }}-admission-create
{{ include "nri-metadata-injection.labels" $ | indent 8 }}
    spec:
      containers:
        - name: create
          image: {{ .Values.jobImage.repository }}:{{ .Values.jobImage.tag }}
          imagePullPolicy: {{ .Values.jobImage.pullPolicy }}
          args:
            - create
            - --host={{ template "nri-metadata-injection.fullname" . }},{{ template "nri-metadata-injection.fullname" . }}.{{ .Release.Namespace }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ template "nri-metadata-injection.fullname" . }}-admission
            - --cert-name=tls.crt
            - --key-name=tls.key
          {{- if .Values.jobImage.volumeMounts }}
          volumeMounts:
          {{- include "tplvalues.render" ( dict "value" .Values.jobImage.volumeMounts "context" $ ) | nindent 10 }}
          {{- end }}
      restartPolicy: Never
      {{- if .Values.jobImage.volumes }}
      volumes:
      {{- include "tplvalues.render" ( dict "value" .Values.jobImage.volumes "context" $ ) | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "nri-metadata-injection.fullname" . }}-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
{{- end }}
