{{- if and (.Values.controlPlane.enabled) (.Values.rbac.create) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{ include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-control-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "newrelic.fullname" . }}-control-plane
subjects:
  - kind: ServiceAccount
    name: {{ template "newrelic.serviceAccountName" . }}-control-plane
    namespace: {{ .Release.Namespace }}
{{- end -}}
