{{- if include "newrelic.common.serviceAccount.create" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nr-ebpf-agent.service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ebpfAgent.serviceAccount.annotations | nindent 4 }}
{{- end }}