---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.service.name" . }}
  labels:
    app: opentelemetry
    component: otel-collector
    {{- include "newrelic.common.labels" . | nindent 4 }}
spec:
  # The OTel collector pod will use a service containing a clusterIP and the configured receiver port to interface via.
  type: ClusterIP
  selector:
    {{- include "newrelic.common.labels.selectorLabels" . | nindent 4 }}
    component: otel-collector
  ports:
    - name: otlp-grpc
      port: {{ .Values.otelCollector.receiverPort }}
      protocol: TCP
      targetPort: {{ .Values.otelCollector.receiverPort }}
