{{- range $subAgentName, $subAgentConfig := .Values.config.subAgents -}}
{{- $name := include "newrelic.common.naming.truncateToDNSWithSuffix" (dict "name" "local-data" "suffix" $subAgentName) }}
{{- if  $subAgentConfig -}}
---
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" $ | nindent 4 }}
    subagent: {{ $subAgentName }}
apiVersion: v1
data:
  local_config: |
    {{- $subAgentConfig.content | toYaml | nindent 4 }}
{{- end -}}
{{- end }}
