{{- range $subAgentName, $subAgentConfig := .Values.agentsConfig -}}
{{- $name := include "newrelic.common.naming.truncateToDNSWithSuffix" (dict "name" "local-data" "suffix" $subAgentName) }}
---
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" $ | nindent 4 }}
    subagent: {{ $subAgentName }}
apiVersion: v1
data:
{{- if not $subAgentConfig.content }}
  local_config: ""
{{- else }}
  local_config: |
    {{- $subAgentConfig.content | toYaml | nindent 4 }}
{{- end }}
{{- end }}
