{{- if include "newrelic-agent-control.auth.secret.shouldTemplate" . -}}
---
kind: Secret
metadata:
  name: {{ include "newrelic-agent-control.auth.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "newrelic.common.labels" . | nindent 4 }}
apiVersion: v1
data:
  {{ include "newrelic-agent-control.auth.secret.privateKey.key" . }}: {{ include "newrelic-agent-control.auth.secret.privateKey.data" . }}
  {{ include "newrelic-agent-control.auth.secret.clientId.key" . }}: {{ include "newrelic-agent-control.auth.secret.clientId.data" . }}
{{- end }}
