{{- if (include "apm-php-agent.areValuesValid" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apm-php-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "apm-php-agent.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.agentPort }}
    protocol: TCP
    targetPort: {{ .Values.agentPort }}
  selector:
{{ include "apm-php-agent.selectorLabels" . | indent 4 }}
{{- end }}
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"
