{{- if .Values.kubelet.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.labels" . | nindent 4 }}
  name: {{ template "newrelic.fullname" . }}-kubelet
data:
  nri-kubernetes-config.yml: |
    {{- .Values.common.config | toYaml | nindent 4 }}
    kubelet:
      enabled: true
    {{- if .Values.kubelet.config -}}
    {{- .Values.kubelet.config | toYaml | nindent 6 }}
    {{- end }}
{{- end }}
