apiVersion: v1
name: redis
version: 1.2.3
appVersion: 1.33.7
# The redis chart is deprecated and no longer maintained. For details deprecation, see the PROCESSES.md file.
deprecated: true
description: DEPRECATED Open source, advanced key-value store. It is often
  referred to as a data structure server since keys can contain strings, hashes,
  lists, sets and sorted sets.
keywords:
  - redis
  - keyvalue
  - database
home: http://redis.io/
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
sources:
  - https://github.com/bitnami/bitnami-docker-redis
maintainers: []
engine: gotpl
