apiVersion: v1
description: A Helm chart to deploy the New Relic metadata injection webhook.
name: nri-metadata-injection
version: 1.0.2
appVersion: 1.2.0
home: https://hub.docker.com/r/newrelic/k8s-metadata-injection
source:
  - https://github.com/newrelic/k8s-metadata-injection
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: douglascamata
  - name: jorik
keywords:
  - infrastructure
  - newrelic
  - monitoring
