{{- $namespaces := include "newrelic.roleBindingNamespaces" . | fromYaml -}}
{{- range $namespaces.roleBindingNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "newrelic.labels" $ | nindent 4 }}
  name: {{ template "newrelic.fullname" $ }}-{{ . }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "newrelic.fullname" $ }}-secrets
subjects:
- kind: ServiceAccount
  name: {{ template "newrelic.serviceAccountName" $ }}-control-plane
  namespace: {{ $.Release.Namespace }}
{{- end -}}
