name: Bump Chart Version

on:
  repository_dispatch:
    types: bump-chart-version

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job that bumps the versions of a chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump Chart & App version
        uses: ./.github/actions/chart-version-bumper
        id: version-bump
        with:
          chart_name: ${{ github.event.client_payload.chart_name }}
          chart_version: ${{  github.event.client_payload.chart_version }}
          app_version: ${{  github.event.client_payload.app_version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.NR_BOT_TOKEN }}
          commit-message: ${{ steps.version-bump.outputs.changeString }}
          title: ${{ steps.version-bump.outputs.changeString }}
          body: ${{ steps.version-bump.outputs.verboseChangeString }}
          branch-suffix: random
          labels: automatic-version-bump
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
