name: Run Makefile

on:
  push:
    branches-ignore:
      - '**master'
    paths:
      - 'charts/nr-k8s-otel-collector/**'

jobs:
  run-makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Helm repositories
        run: |
          helm repo add newrelic https://helm-charts.newrelic.com
          helm repo add k8s-agents-operator https://newrelic.github.io/k8s-agents-operator
          helm repo add k8s-metadata-injection https://newrelic.github.io/k8s-metadata-injection
          helm repo add newrelic-infra-operator https://newrelic.github.io/newrelic-infra-operator          
          helm repo add newrelic-k8s-metrics-adapter https://newrelic.github.io/newrelic-k8s-metrics-adapter
          helm repo add newrelic-prometheus-configurator https://newrelic.github.io/newrelic-prometheus-configurator
          helm repo add nr-helm-charts https://newrelic.github.io/helm-charts
          helm repo add nri-kube-events https://newrelic.github.io/nri-kube-events
          helm repo add nri-kubernetes https://newrelic.github.io/nri-kubernetes
          helm repo add nri-prometheus https://newrelic.github.io/nri-prometheus
          helm repo add fluxcd-community https://fluxcd-community.github.io/helm-charts
          helm repo add pixie-operator https://pixie-operator-charts.storage.googleapis.com
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Run Makefile target 'generate-examples'
        run: |
          make generate-examples

      - name: Run Makefile target 'check-examples'
        run: |
          make check-examples

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update generated examples via GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
