apiVersion: v1
description: A Helm chart to deploy the New Relic Infrastructure Kubernetes Operator.
name: newrelic-infra-operator
version: 0.1.0
appVersion: 1.4.0
home: https://hub.docker.com/r/newrelic/newrelic-infra-operator
sources:
  - https://github.com/newrelic/newrelic-infra-operator
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: douglascamata
  - name: paologallinaharbur
  - name: davidbrota
  - name: gsanchezgavier
  - name: roobre
keywords:
  - infrastructure
  - newrelic
  - monitoring
